import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEMORY_STORE_PATH = os.path.join(BASE_DIR, "data/memory")
os.makedirs(MEMORY_STORE_PATH, exist_ok=True)

WORKING_MEMORY_EXPIRE = 30
TOOL_CONTEXT_EXPIRE = 5
SHORT_TERM_MEMORY_EXPIRE = 7
LONG_TERM_MEMORY_EXPIRE = -1

MAX_WORKING_MEMORY = 500
MAX_SHORT_TERM = 200
LONG_TERM_COMPRESS_THRESHOLD = 5
MAX_CONVERSATION_TURNS = 6
MAX_CONVERSATION_SUMMARY_CHARS = 2000

MEMORY_ARCHIVE_PATH = os.path.join(MEMORY_STORE_PATH, "archive")
os.makedirs(MEMORY_ARCHIVE_PATH, exist_ok=True)

AGENT_TASK_PREFIX = "agent_task_"
DEFAULT_USER_ID = "student_user"
